version: '3.7'

services:
  postgres:
    image: postgres:16.3
    container_name: smart-wardrobe.postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - smart-wardrobe-network

  smart-wardrobe.api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: smart-wardrobe
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
      BUILD_CONFIGURATION: Development
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - smart-wardrobe-network
    command: ["dotnet", "API.dll"]
  
  smart-wardrobe.frontend:
    build:
      context: ../frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - smart-wardrobe.api
    networks:
      - smart-wardrobe-network
  
  smart-wardrobe.ml.vision:
    build:
      context: ../clothing-vision-service
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    container_name: smart-wardrobe.ml.vision
    ports:
      - "8000:8000"
    networks:
      - smart-wardrobe-network
    restart: always
    
  smart-wardrobe.ml.visual-search:
    build:
      context: ../ml-visual-search
      dockerfile: Dockerfile
    container_name: smart-wardrobe.ml.visual-search
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8003:8003"
    volumes:
      - ../ml-visual-search/models:/app/models
    networks:
      - smart-wardrobe-network
    restart: always
    
  smart-wardrobe.ml.capsule:
    build:
      context: ../ml-capsule-generator
      dockerfile: Dockerfile
    container_name: smart-wardrobe.ml.capsule
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8001:8001"
    networks:
      - smart-wardrobe-network
    restart: always
    
  smart-wardrobe.ml.recommendation:
    build:
      context: ../ml-smart-recommendation
      dockerfile: Dockerfile
    container_name: smart-wardrobe.ml.recommendation
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8002:8002"
    networks:
      - smart-wardrobe-network
    restart: always

networks:
  smart-wardrobe-network:
    driver: bridge
