version: '3.7'

services:
  postgres:
    image: postgres:16.3
    container_name: smart-wardrobe.postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - smart-wardrobe-network

  smart-wardrobe.api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: smart-wardrobe
    environment:
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_ENVIRONMENT: Development
      BUILD_CONFIGURATION: Development
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - smart-wardrobe-network
    command: ["dotnet", "API.dll"]
  
  smart-wardrobe.frontend:
    build:
      context: ../frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - smart-wardrobe.api
    networks:
      - smart-wardrobe-network

networks:
  smart-wardrobe-network:
    driver: bridge
